services:
  forohub_db:
    container_name: forohub_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: forohub
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
